### ISSUE TITLE
Generate Label from Segmentation

### ISSUE THREAD

**Issue by Amin-Tgz** [DanielHfnr/Carla-Object-Detection-Dataset#1]
Hi,
How you generate label from segmentation?
would you please share codes of that?
Thanks in advance

**Comment by Xiang95** [comment]
@Amin-Tgz have you figure out how to get the label?

**Comment by Amin-Tgz** [comment]
@Xiang95 Somewhat,but IMO the best way is manual annotation because create label from segmentation or 3d coordinate cause problem in bounding box size and you must correct plenty of images. unfortunately i removed my codes so have nothing to share, sorry :(
also i suggest you to look at this [link](https://github.com/Amin-Tgz/awesome-CARLA).

**Comment by Xiang95** [comment]
> @Xiang95 Somewhat,but IMO the best way is manual annotation because create label from segmentation or 3d coordinate cause problem in bounding box size and you must correct plenty of images. unfortunately i removed my codes so have nothing to share, sorry :(
> also i suggest you to look at this [link](https://github.com/Amin-Tgz/awesome-CARLA).

thank you for your kindly reply. For my project i need the 3D Boundingbox Information, the thing is that carla provides all vehicles' information in the simulator not the information  in the current camera view. Since @DanielHfnr somehow managed to get the labels of the vehicles in the camera view, I though you guys maybe figured out a way to deal with this issue. 

Anyway, thanks a lot. I will check the link later.

**Comment by DanielHfnr** [comment]
Hi  @Amin-Tgz and @Xiang95! Sorry for the late answer, i havent noticed that until now. 
I created the labels for this dataset automatically with a python script. Unfortunately after creating the labels were not accurate enough to use it directly. Therefore sometimes manually adjusting the labels for each image was necessary.

The complete way the create this dataset was basically as follows:

- Run CARLA and let the car drive in autopilot mode.

- While the car is driving around export the rgb-image as well as the corresponding semantic segmentation image every few seconds.

- Now I had lots of images with the semantic segmentation information

- I then created a python script that opens the semantic segmentation image one by one to create bounding boxes for the classes I wanted with opencv. 

- There was a little bit of filtering involved (only use areas with specific size, aspect rations and so on)

- Export the labels for each image in a xml file in the pascal voc format.

- After doing this for all the images I had the dataset. Some of the lables were wrong and others were not accurate enough. I opened the rgb image with the corresponding label xml file in labelImg to see the results.

- A lot of labels were already pretty satisfying. I opened every image one after the other and deleted invalid labels and moved others a little bit to be more accurate. 

I then had this dataset which was pretty good. As you can see there is still a little work to manually adjust the labels. But creating the labels automatically before saved me a lot of time, because adjusting didnt take so much time.

I will have a look and maybe I can provide you with the python scripts, but they are a little messy at the moment. :-)

**Comment by Xiang95** [comment]
> Hi @Amin-Tgz and @Xiang95! Sorry for the late answer, i havent noticed that until now.
> I created the labels for this dataset automatically with a python script. Unfortunately after creating the labels were not accurate enough to use it directly. Therefore sometimes manually adjusting the labels for each image was necessary.
> 
> The complete way the create this dataset was basically as follows:
> 
>     * Run CARLA and let the car drive in autopilot mode.
> 
>     * While the car is driving around export the rgb-image as well as the corresponding semantic segmentation image every few seconds.
> 
>     * Now I had lots of images with the semantic segmentation information
> 
>     * I then created a python script that opens the semantic segmentation image one by one to create bounding boxes for the classes I wanted with opencv.
> 
>     * There was a little bit of filtering involved (only use areas with specific size, aspect rations and so on)
> 
>     * Export the labels for each image in a xml file in the pascal voc format.
> 
>     * After doing this for all the images I had the dataset. Some of the lables were wrong and others were not accurate enough. I opened the rgb image with the corresponding label xml file in labelImg to see the results.
> 
>     * A lot of labels were already pretty satisfying. I opened every image one after the other and deleted invalid labels and moved others a little bit to be more accurate.
> 
> 
> I then had this dataset which was pretty good. As you can see there is still a little work to manually adjust the labels. But creating the labels automatically before saved me a lot of time, because adjusting didnt take so much time.
> 
> I will have a look and maybe I can provide you with the python scripts, but they are a little messy at the moment. :-)

thanks a lot for your explanation. I did check the link provided by @Amin-Tgz yesterday and I found something really useful for my project. It works for me, Maybe you can have a look too. https://github.com/enginBozkurt/carla-training-data
