### ISSUE TITLE
What was the camera setup?

### ISSUE THREAD

**Issue by marcoruizrueda** [DanielHfnr/Carla-Object-Detection-Dataset#3]
Hi @DanielHfnr Can you please indicate the camera settings that you used to generate your images from Carla, these are mine:

`"type": "sensor.camera.rgb",
  "id": "front_color",
  "x": -0.556, "y": 0.0, "z": 1.683, "yaw": 0.0,
  "image_size_x": 1280,
  "image_size_y": 720,
  "fov": 52.0,
  "sensor_tick": 0.1`

My TF model trained with your images is accurate in predicting images from my validation subset and external images (google images), but not on images coming directly from Carla. Best regards.

**Comment by DanielHfnr** [comment]
Hi @marcoruizrueda, 

sorry for the late response. Actually Im not quite sure, because I had to setup my pc again. 
But I probably used the default sensor settings:

"spawn_point": {"x": 2.0, "y": 0.0, "z": 2.0, "roll": 0.0, "pitch": 0.0, "yaw": 0.0},
"image_size_x": 640,
"image_size_y": 380,
"fov": 90.0,
"sensor_tick": 0.05
               
Best,
Daniel
